version: '3.7'

services:
  db_posgtgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: system

  consul:
    image: consul:1.7.1
    ports:
      - 8500:8500

  playground:
    restart: always
    image: architectureplayground/playground
    ports:
      - 7999:7999
    environment:
      # compose environment variables https://docs.docker.com/compose/environment-variables/
      - POSTGRES_HOST=db_posgtgres
      - CONSUL_HOST=consul
    depends_on:
      - db_posgtgres
      - consul
