spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    driverClassName: org.postgresql.Driver
    username: postgres
    password: system
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      default_schema: public
