spring:
  application:
    name: playground-service
  datasource:
    # each microservice should have its own database
    # to prevent clashing of the migration schema version.
    url: jdbc:postgresql://localhost:5432/playground
    driverClassName: org.postgresql.Driver
    username: postgres
    password: system
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      default_schema: public
  flyway:
    schemas: public, playground
  cloud:
    consul:
      host: localhost
      port: 8500

server:
  port: 7999

springdoc:
  swagger-ui:
    path: /openapi-ui.html

